version: "3.3"

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=UTC
      - TOKEN=${BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: alpine:latest
    container_name: sqlite_db
    volumes:
      - ./data:/data
    command: >
      sh -c "mkdir -p /data && chmod 777 /data && tail -f /dev/null"
    restart: unless-stopped
