version: "3.3"

services:
  bot:
    build: .
    container_name: telegram_bot
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - TZ=UTC
      - TOKEN=${BOT_TOKEN}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: plans_db
      POSTGRES_USER: plans_user
      POSTGRES_PASSWORD: plans_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
